version: 0.0
os: linux
files:
  - source: /
    destination: /srv/myhubot
hooks:
  ApplicationStart:
    - location: deploy/application-start.sh
  ValidateService:
    - location: depoy/validate-service.sh
